---
- hosts: all
  become: yes
  vars:
    networkInterfaceVal: "{{ networkInterface }}"
    etcHostsFileContentList: "{{ etcHostsFileContent.splitlines() }}"
  tasks:
    - name: Update etc hosts file with network interface
      shell: |
        #!/bin/bash
        set -e
        IFNAME={{ networkInterfaceVal }}
        HOSTNAME=$(hostname)
        ADDRESS="$(ip -4 addr show $IFNAME | grep "inet" | head -1 |awk '{print $2}' | cut -d/ -f1)"
        echo "ifname -> $IFNAME addr -> $ADDRESS hostname -> $HOSTNAME" >> /tmp/data.txt
        echo "############### BEFORE update /etc/hosts ###############" >> /tmp/data.txt
        cat /etc/hosts >> /tmp/data.txt
        sed -e "s/^.*${HOSTNAME}.*/${ADDRESS} ${HOSTNAME} ${HOSTNAME}.local/" -i /etc/hosts

        # remove ubuntu entry
        sed -e '/^.*ubuntu.*/d' -i /etc/hosts
        
        echo "############### AFTER update /etc/hosts ###############" >> /tmp/data.txt
        cat /etc/hosts >> /tmp/data.txt
    - name: Update etc hosts file with hostnames
      shell: "echo {{ item }} >> /etc/hosts"
      with_items:
      - "{{ etcHostsFileContentList }}"
      notify:
      - update_dns_handler
  handlers:
    - name: update_dns_handler
      shell: |
        #!/bin/bash
        
        sed -i -e 's/#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
        
        service systemd-resolved restart