---

- hosts: kubemaster
  become: yes
  roles:
    - role: ansible-role-linux-kubernetes

- hosts: kubeworker
  become: yes
  roles:
    - role: ansible-role-linux-kubernetes

- hosts: kubemaster
  become: yes
  roles:
    - role: kubetools-install